export const FINANCE_CONSTANTS = {
  MIN_TOPUP_AMOUNT: 500,
  MAX_WALLET_BALANCE: 10_000_000,
  DEFAULT_CURRENCY: 'NGN',
  KOBO_MULTIPLIER: 100,
  MAX_INSTALLMENTS: 12,
  RECEIPT_PREFIX: 'RCPT',
  PAYSTACK_BASE_URL: 'https://api.paystack.co',
  PAGINATION_DEFAULT_PAGE: 1,
  PAGINATION_DEFAULT_LIMIT: 20,
  PAGINATION_MAX_LIMIT: 100,
};
